#+TITLE: dangerzone-client README

* What is this?

This is an application (command-line & desktop GUI), that converts suspicious documents to safe trusted PDF documents.

* What is required?

This application relies on common Rust tooling for builds and a container engine solution for execution:
- For compilation, you need a recent version of the Rust toolchain ([[https://www.rust-lang.org/tools/install][rustc]] compiler and [[https://doc.rust-lang.org/cargo/][cargo]]).
- For execution, it is assumed that the =dangerzone-container= application is deployed under [[https://www.docker.com/][Docker]] or [[https://podman.io/][Podman]] or [[https://github.com/lima-vm/lima][Lima]].

Please note that this has *been mostly tested under Linux* so far ([[https://voidlinux.org/][Void Linux]] & [[https://sparkylinux.org/][SparkyLinux]] more specifically).

* How to build this?

At the root of this project, open a command prompt and type =cargo build=.

* How to run this?

Please refer to the top level folder for desktop or command-line screenshots.

** Desktop usage

The user interface is built with the [[https://www.fltk.org/][FLTK]] toolkit because it's lightweight and /relatively/ easy to use.

The user interface doesn't have all the command-line application features (=OCI image= location, etc.).

#+begin_src sh
./target/debug/dangerzone-gui
#+end_src

** Command line usage

*** Help information

#+begin_src sh
  ./target/debug/dangerzone-cli -h
#+end_src

*** Sample general usage

In the example below, a suspicious PDF file is converted to a searchable PDF ([[https://en.wikipedia.org/wiki/Optical_character_recognition][OCR]]), instead of just PDF images (=ocr-lang= parameter).
/OCR/ is a time consuming task in comparison to just generating PDF images for pages of the original input (text recognition and additional processing steps).

#+begin_src sh
   cp ../dangerzone-testdata/gnus-logo.pdf suspicious_file.pdf
  ./target/debug/dangerzone-cli --input-filename suspicious_file.pdf --ocr-lang eng
#+end_src
