FROM docker.io/rust:1.70.0-bookworm

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y g++-mingw-w64-x86-64 binutils-mingw-w64-x86-64 \
    && DEBIAN_FRONTEND=noninteractive apt-get clean \
    && rustup target add x86_64-pc-windows-gnu


