FROM docker.io/rust:1.67.0-bullseye

RUN apt update && apt upgrade -y \
    && apt install -y g++-mingw-w64-x86-64 binutils-mingw-w64-x86-64 \
    && apt clean \
    && rustup target add x86_64-pc-windows-gnu \
    && rustup toolchain install stable-x86_64-pc-windows-gnu \
    && apt clean
