# CI_CD

* Overview
It is highly desirable to be able to generate all the build artifacts automatically, regardless of the target operating system (Linux, MacOS or Windows).

The current build machine is running Ubuntu with the following software:
- podman as the container solution, used to build all artifacts inside containers
- convert Scale icon images
- icnsutils (turn application icon to icns format used on MacOS)

* Targeted Operating Systems

* Linux 

The GUI is built on a Centos 7 container image to achieve maximal binary compatibility across Linux distributions
- The GUI binary cannot be statically linked
- The libc versions (GLibc and alternatives) vary significantly across distributions, preventing the apps to run

  [[https://github.com/linuxdeploy/linuxdeploy][LinuxDeploy]] is the solution adopted for creating an [[https://docs.appimage.org/][AppImage]] for the GUI. The AppImage requires [[https://wiki.archlinux.org/title/FUSE][Fuse]] tools to run.
  
* Windows

The performance, binaries and other details hasn't been assessed, ut this seems to be running just fine.

* MacOS notes

The performance, binaries and other details hasn't been assessed, ut this seems to be running just fine.
